META:
  CLASSES: {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}
  SOURCE: 'MT'
  SOURCE_PATH: 'datasets/MNIST.bin'
  TARGET: 'MM'
  TARGET_PATH: 'datasets/MNIST-M.bin'
DATA:
  TRAIN_DATASET: 'digitpair'
  TRAIN_DATASET_PARAMS:
    SOURCE_NUM: 0
    TARGET_NUM: 100
    SAMPLE_RATIO: 3
  TEST_DATASET: 'digit'
  TEST_DATASET_PARAMS:
    SOURCE_NUM: -1
    TARGET_NUM: 0
  BATCH_SIZE: 256
NETWORK:
  NAME: 'LENETPLUS'
  NETWORK_PARAMS:
    CLASSES: 10
    FEATURE_SIZE: 256
    USE_L2N: False
TRAIN:
  OPTIM: 'sgd'
  OPTIM_PARAMS:
    LEARNING_RATE: 0.01
    WD: 0.0001
    MOMENTUM: 0.9
  LOG_ITV: 500