META:
  CLASSES: {'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9}
  SOURCE: 'MT'
  SOURCE_PATH: 'datasets/MNIST.bin'
  TARGET: 'US'
  TARGET_PATH: 'datasets/USPS.bin'
DATA:
  TRAIN_DATASET: 'digitpair'
  TRAIN_DATASET_PARAMS:
    SOURCE_NUM: 2000
    TARGET_NUM: 10
    SAMPLE_RATIO: 5
  TEST_DATASET: 'digit'
  TEST_DATASET_PARAMS:
    SOURCE_NUM: -1
    TARGET_NUM: 0
  BATCH_SIZE: 256
NETWORK:
  NAME: 'CONV2'
  NETWORK_PARAMS:
    CLASSES: 10
    FEATURE_SIZE: 256
    DROPOUT: 0.5
TRAIN:
  RNG_SEED: 10
  OPTIM: 'sgd'
  OPTIM_PARAMS:
    LEARNING_RATE: 0.001
    WD: 0.0001
    MOMENTUM: 0.9
  DSNE:
    MARGIN: 1
    FN: True
  MAX_EPOCH: 50
  LOG_ITV: 100
